# Specify api data from my.telegram.org
[api]
id = ""
hash = ""

# Specify responses to send
# Remove fields as a whole if not needed
[messages]
respond_only_once = true
for_known = "Hey you!"
for_others = "Hey stranger!"
footer = "\n---------------\nSent automatically with [Pong](https://github.com/lesterrry/pong)"

# Specify people you know
# Arrays accept usernames (like '@user'), phone numbers (like +1234...), ids (like 123)
# Do not remove fields, leave them empty
[contacts]
known = [ "@user", "+123456789", "123456789" ]
ignore = [ "+123456789" ]

[service]
# If you enable logs, all messages Pong responded to will be saved to a local file
logging_enabled = false
# You may also enable integration with Cronitor
cronitor_integrated = true
cronitor_key = ""
cronitor_id = ""
cronitor_hostname = "iMac"